// Generated by LiveScript 1.2.0
var AskKK, firebase;
AskKK = require('../lib/askkk').AskKK;
module.exports.firebase = firebase = new (require('firebase'))('https://askkkkk.firebaseio.com/');
module.exports.ask = new AskKK({
  firebase: firebase
});
module.exports.resetPetitions = function(onComplete){
  return firebase.child('petitions').remove(function(){
    return onComplete();
  });
};
module.exports.resetCandidates = function(onComplete){
  return firebase.child('candidates').set({
    "-JFuCKMKOH_eCspPxRe1": {
      "name": "連勝文",
      "email": "lsw@gov.tw",
      "id": "-JFuCKMKOH_eCspPxRe1"
    },
    "-JFuCJcAoUNFQY9NEHZ4": {
      "name": "柯文哲",
      "email": "kk@med.ntu.edu.tw",
      "id": "-JFuCJcAoUNFQY9NEHZ4"
    }
  }, function(error){
    return onComplete();
  });
};