// Generated by LiveScript 1.2.0
var AskKK, firebase;
AskKK = require('../lib/askkk').AskKK;
module.exports.firebase = firebase = new (require('firebase'))('https://askkkkk.firebaseio.com/');
module.exports.ask = new AskKK({
  firebase: firebase
});
module.exports.resetPetitions = function(onComplete){
  return firebase.child('petitions').remove(function(){
    return onComplete();
  });
};