// Generated by LiveScript 1.2.0
var AskKK, assert, firebase, ask, resetCandidate;
AskKK = require('../lib/askkk').AskKK;
assert = require('assert');
firebase = new (require('firebase'))('https://askkkkk.firebaseio.com/');
ask = new AskKK({
  firebase: firebase
});
resetCandidate = function(onComplete){
  return firebase.child('candidates').set({
    1: {
      "name": "柯文哲",
      "email": "kk@med.ntu.edu.tw",
      "id": 1
    },
    2: {
      "name": "連勝文",
      "email": "lsw@gov.tw",
      "id": 2
    }
  }, function(error){
    return onComplete();
  });
};