// Generated by LiveScript 1.2.0
var assert, ref$, ask, firebase, keys;
assert = require('assert');
ref$ = require('./askkk'), ask = ref$.ask, firebase = ref$.firebase;
keys = require('prelude-ls').keys;
describe('Candidate', function(){
  return describe('get', function(){
    var x$;
    x$ = it;
    x$('should get candidate info for given id.', function(){
      return ask.getCandidate("-JFxrKQo3Qg19zsW73b1", function(data){
        assert.equal(data["state"], 'join');
        return assert.equal(data["partyEng"], 'NONE');
      });
    });
    x$('should get all candidate info when id is null', function(){
      return ask.getCandidate(null, function(data){
        assert.equal(keys(data).length, 6);
        assert.equal(data["-JFuCKMKOH_eCspPxRe1"].name, '連勝文');
        return assert.equal(data["-JFxrKQo3Qg19zsW73b1"].name, '馮光遠');
      });
    });
    return x$;
  });
});