// Generated by LiveScript 1.2.0
var assert, ref$, ask, firebase;
assert = require('assert');
ref$ = require('./askkk'), ask = ref$.ask, firebase = ref$.firebase;
describe('Petition', function(){
  return describe('create', function(){
    var x$;
    x$ = it;
    x$('should write petition info', function(done){
      return ask.createPetition({
        title: 'hello, world!',
        story: 'Let us all say hello!',
        candidates: ["-JFuCJcAoUNFQY9NEHZ4"]
      }, function(data){
        return ask.getPetition(data.id, function(data){
          assert.equal(data.title, 'hello, world!');
          assert.equal(data.story, 'Let us all say hello!');
          assert.equal(data.candidates["-JFuCJcAoUNFQY9NEHZ4"], true);
          return done();
        });
      });
    });
    x$('should add to candidate pentition list', function(done){
      return ask.createPetition({
        title: 'hello',
        story: 'hello',
        candidates: ["-JFuCKMKOH_eCspPxRe1"]
      }, function(data){
        return firebase.child('candidate_meta/-JFuCKMKOH_eCspPxRe1/petitions').child(data.id).once('value', function(snapshot){
          assert(snapshot.val());
          return done();
        });
      });
    });
    return x$;
  });
});