// Generated by LiveScript 1.2.0
var assert, ask;
assert = require('assert');
ask = require('./askkk').ask;
describe('Petition', function(){
  return describe('create', function(){
    var x$;
    x$ = it;
    x$('should write petition info', function(done){
      return ask.createPetition({
        title: 'hello, world!',
        story: 'Let us all say hello!',
        candidates: {
          1: true,
          2: true
        }
      }, function(data){
        assert(data.id);
        return ask.getPetition(data.id, function(data){
          assert.equal(data.title, 'hello, world!');
          assert.equal(data.story, 'Let us all say hello!');
          return done();
        });
      });
    });
    return x$;
  });
});