// Generated by LiveScript 1.2.0
var assert, ref$, ask, firebase;
assert = require('assert');
ref$ = require('./askkk'), ask = ref$.ask, firebase = ref$.firebase;
describe('Response', function(){
  return describe('respond', function(){
    var x$;
    x$ = it;
    x$('should attach a response to to petition', function(done){
      return ask.createPetition({
        title: 'Should we promote world peace?',
        story: null,
        candidates: ["-JFuCJcAoUNFQY9NEHZ4"]
      }, function(data){
        var petitionId;
        petitionId = data.id;
        return ask.respond({
          petitions: [petitionId],
          content: 'No, we should limit ourselves to this Galaxy.'
        }, function(error, data){
          return firebase.child('petitions').child(petitionId).child('responses').child(data.id).once('value', function(snapshot){
            assert(snapshot.val());
            return done();
          });
        });
      });
    });
    return x$;
  });
});