// Generated by LiveScript 1.2.0
var assert, ref$, ask, firebase;
assert = require('assert');
ref$ = require('./askkk'), ask = ref$.ask, firebase = ref$.firebase;
describe('Signature', function(){
  return describe('sign', function(){
    var x$;
    x$ = it;
    x$('should be ok to sign', function(done){
      return ask.createPetition({
        title: 'hello, world!',
        story: 'Let us all say hello!',
        candidates: {
          1: true,
          2: true
        }
      }, function(data){
        var petitionId;
        petitionId = data.id;
        return ask.sign(petitionId, function(data){
          return firebase.child('petition_meta').child(petitionId).child('signatures/1').on('value', function(snapshot){
            assert(snapshot.val());
            return done();
          });
        });
      });
    });
    return x$;
  });
});