// Generated by LiveScript 1.2.0
var assert, ref$, ask, firebase, resetUsers;
assert = require('assert');
ref$ = require('./askkk'), ask = ref$.ask, firebase = ref$.firebase;
resetUsers = function(onComplete){
  return firebase.child('users/-JFpHNE3D4AIERz6lo_4').set({
    name: 'soidid',
    email: 'soidid@earth',
    id: '-JFpHNE3D4AIERz6lo_4'
  }, function(error){
    return onComplete();
  });
};
describe('User', function(){
  return describe('create', function(){
    var x$;
    x$ = it;
    x$('should write user info', function(done){
      return resetUsers(function(){
        return ask.createUser({
          name: 'KP',
          email: 'kp@med.ntu.edu.tw'
        }, function(data){
          return ask.getUser(data.id, function(data){
            assert.equal('KP', data.name);
            assert.equal('kp@med.ntu.edu.tw', data.email);
            return done();
          });
        });
      });
    });
    return x$;
  });
});