// Generated by LiveScript 1.2.0
var x$;
x$ = angular.module('conf', []);
x$.factory('conf', function(){
  return {
    siteTitle: '市長，給問嗎？',
    siteSlogan: '整個城市，都是我的質詢台',
    footerLink: {
      link: 'http://watchout.tw/',
      title: 'Watchout 沃草'
    },
    firebase: 'https://askkkkk.firebaseio.com/'
  };
});