// Generated by LiveScript 1.2.0
var x$;
x$ = angular.module('conf', []);
x$.factory('conf', function(){
  return {
    siteTitle: '零時．全民記者會',
    siteSlogan: '寫程式改造社會．拆政府原地重建',
    footerLink: {
      link: 'http://g0v.tw/',
      title: 'g0v'
    },
    firebase: ''
  };
});