// Generated by LiveScript 1.2.0
var values, askServices, ref;
values = require('prelude-ls').values;
askServices = angular.module('askServices', ['firebase']);
ref = new Firebase('https://askkkkk.firebaseio.com/');
askServices.factory('candidateService', [
  '$firebase', function($firebase){
    var service;
    return service = $firebase(ref.child('candidates'));
  }
]);
askServices.factory('askLoginService', ['$firebase', function($firebase){}]);
/**
 * Filter an object to an array of its keys (properties) except those given be AngularFire.
 */
askServices.filter('toKeys', function(){
  return function(input, attributes){
    if (!angular.isObject(input)) {
      return input;
    }
    return keys(input).filter(function(it){
      return it[0] !== '$';
    });
  };
});